version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  users-service:
    build: ./users-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres

  products-service:
    build: ./products-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres

  orders-service:
    build: ./orders-service
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - users-service
      - products-service
      - orders-service

volumes:
  postgres_data: